#!/usr/bin/env ruby
# Compile HAML and SASS and copy all files to public/

require 'pathname'
require 'yaml'
require 'rubygems'
require 'haml'
require 'sass'
require 'maruku'

ROOT    = Pathname.new(__FILE__).dirname.parent.realpath
PROJECT = ROOT.parent
CONTENT = ROOT.join('content')
LAYOUT  = ROOT.join('layout')
PUBLIC  = ROOT.join('public')

def production?
  'production' == ARGV.first
end

def readme(path)
  path = path[1..-1] + 'README.md'
  Maruku.new(File.read(PROJECT.join(path))).to_html
end

def menu(title, link)
  options = ''
  if link == @page
    title += '<div></div>'
    options = ' class="open"'
  end
  '<a href="' + link + '"' + options + '>' + title + '</a>'
end

def build
  PUBLIC.rmtree if PUBLIC.exist?
  PUBLIC.mkpath

  path = LAYOUT + 'layout.html.haml'
  layout = Haml::Engine.new(File.read(path), :ugly => true)

  Pathname.glob(CONTENT.join('**/*.haml').to_s) do |haml|
    @page = haml.basename('.haml').to_s
    file = PUBLIC + haml.relative_path_from(CONTENT).dirname + @page
    file.dirname.mkpath
    File.open(file, 'w') do |io|
      content = Haml::Engine.new(File.read(haml), :ugly => true).render(self)
      io.write(layout.render(self) { content })
    end
  end

  Pathname.glob(LAYOUT.join('**/*.sass').to_s) do |sass|
    content = File.read(sass)
    css = PUBLIC + sass.relative_path_from(LAYOUT).dirname +
          (sass.basename('.sass').to_s + '.css')
    css.dirname.mkpath
    File.open(css, 'w') do |io|
      io.write Sass::Engine.new(content).render
    end
  end

  Pathname.glob(LAYOUT.join('**/*').to_s, File::FNM_DOTMATCH) do |from|
    next if from.directory?
    next if '.sass' == from.extname or '.haml' == from.extname
    to = PUBLIC + from.relative_path_from(LAYOUT)
    to.dirname.mkpath
    to.make_link(from)
  end
end

build
